version: '2'
services:
  axon-postgresql:
    image: postgres:12.3
    environment:
      - POSTGRES_USER=Axon
      - POSTGRES_PASSWORD=axon
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - 5432:5432
